### ISSUE TITLE
 not opening in the browser

### ISSUE THREAD

**Issue by meetgyn** [Secure-Compliance-Solutions-LLC/gvm-logstash#3]
Good afternoon my friend.
I downloaded some tests, but it is not opening in the browser. What would be the address? localhost? 
![image](https://user-images.githubusercontent.com/3695608/147783084-e13601d0-c16c-4c98-9f60-a5385aee5367.png)

**Comment by Dexus** [comment]
you doing it wrong, run this image as a sidecar container with the GVM Container and a elasticsearch container.
